In [1]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import FloatTensor
from torch.autograd import Variable

In [2]:
x=t.empty(5,3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  5.6009e-26,  4.5618e-41],
        [ 5.3996e-26,  4.5618e-41,  8.1460e-26],
        [ 4.5618e-41,  5.4000e-26,  4.5618e-41],
        [ 7.7213e+28,  4.5618e-41,  0.0000e+00]])


In [3]:
a = t.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([ 1.,  1.,  1.,  1.,  1.])
[ 1.  1.  1.  1.  1.]


In [4]:
x = torch.rand(1)
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([ 1.0051], device='cuda:0')
tensor([ 1.0051], dtype=torch.float64)


In [2]:
class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [3]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight

10
torch.Size([6, 1, 5, 5])


In [4]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.1547, -0.0731,  0.0632,  0.1185,  0.0356,  0.0016,  0.1729,
          0.0052, -0.0228,  0.1265]])


In [6]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [5]:
a = Variable(FloatTensor([4]))
weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

In [6]:
L.backward()

In [19]:
for index, weight in enumerate(weights, start=1):
    #gradient, garbage = weight.grad.data
    np.shape(weight.grad.data)
    #print "Gradient of w{index} w.r.t to L: {gradient}".format(index,gradient)

In [14]:
torch.randn(1,1,32,32)

tensor([[[[-0.7175, -0.4513, -0.4201,  ...,  0.5683, -0.5986,  0.7234],
          [ 0.2157, -0.9009, -1.4403,  ...,  0.1675,  0.9184,  0.7791],
          [-0.6243,  1.9364,  1.8012,  ..., -0.4839,  1.2344,  1.0370],
          ...,
          [ 1.8106,  2.0938,  0.2682,  ...,  0.7793, -0.4200,  1.0455],
          [ 0.6321, -0.0478,  0.0160,  ..., -0.4727, -0.2064,  0.1710],
          [ 0.7367, -2.3436, -0.5430,  ...,  0.0865,  1.4857, -1.9288]]]])